fastlane_version '2.19.1' rescue update_fastlane

default_platform :ios

# Fix: Could not open terminal for stdout: $TERM not set
ENV['TERM'] ||= 'dumb'

require_relative 'fastlane_utils'
require_relative 'xcode_8_xctestrun'
require_relative 'fbsimctl'
require_relative 'earl_grey_data'
Xcode8.runner = self.runner

SCHEME = 'buttonTests'
APP_BUNDLE_ID = 'org.reactjs.native.example.button'

platform :ios do

  desc 'build-for-testing'
  lane :build_for_testing do
    Xcode8.build_for_testing(scheme: SCHEME)
  end

  desc %q(test-without-building.
Requires fbsimctl
brew tap facebook/fb
brew install fbsimctl --HEAD)
  lane :test_without_building do
    video_out = File.expand_path(File.join(__dir__, '..', 'video.mp4'))

    video_out = ENV['BITRISE_DEPLOY_DIR'] if bitrise?

    simulator = FBSimctl.new video_out: video_out

    begin
      simulator.start_server
      simulator.start_recording

      Xcode8.test_without_building(scheme: SCHEME)
    ensure
      simulator.stop_recording
      simulator.stop_server
      ui_important "Saved video to: #{video_out}"

      EarlGreyData.new.collect APP_BUNDLE_ID
    end
  end
end
